# Generated by Django 4.2.4 on 2023-08-24 07:08

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Currently working with hospital?', verbose_name='Status')),
            ],
            options={
                'db_table': 'consultant',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('display_picture', models.ImageField(upload_to=people.models.display_picture_path)),
                ('linkedin', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Currently working with hospital?', verbose_name='Status')),
            ],
            options={
                'db_table': 'management',
            },
        ),
    ]
