# Generated by Django 4.2.4 on 2023-08-24 16:07

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_consultant_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='display_picture',
            field=models.ImageField(null=True, upload_to=people.models.consultant_picture_path),
        ),
    ]
