# Generated by Django 4.2.4 on 2023-08-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
